export const {
  QIAN_WEN_TEXT_MODEL_NAME,
  QIAN_WEN_API_URL,
  QIAN_WEN_API_KEY,
  GOOGLE_API_KEY,
  GOOGLE_IMAGE_API_KEY,
  UPLOAD_IMAGE_PUBLIC_KEY,
  UPLOAD_IMAGE_PRIVATE_KEY,
  UPLOAD_IMAGE_HOST,
  UPSTASH_VECTOR_REST_URL,
  UPSTASH_VECTOR_REST_TOKEN,
  SUPABASE_URL,
  SUPABASE_SERVICE_ROLE_KEY,
  ZHIPU_API_KEY
} = process.env;

